## Numpy: Numeric + Python의 약자, 수학 및 과학 연산 라이브러리
- 배열이나 행렬 계산에 필요한 함수 제공
- 수열 데이터를 다룰 때 용이, 이후에 Pandas에서 DataFrame 형태로 사용함
- 다차원 배열(Array)을 다룰 때 주로 사용함 (인공 신경망, 비정형 데이터 처리, 자연어 처리 등)
- 코어 부분이 C로 구현되어 동일한 연산을 하더라도 Python에 비해 속도가 빠름
- 라이브러리에 구현되어있는 함수들을 활용해 짧고 간결한 코드 작성 가능

In [5]:
test = [15, 20, 25]
test
type(list)
for i in range(len(test)):
    test[i] += 5
test

[20, 25, 30]

In [9]:
[tes + 5 for tes in test] 

[25, 30, 35]

In [7]:
!pip install numpy


[notice] A new release of pip is available: 24.0 -> 24.1.2
[notice] To update, run: python.exe -m pip install --upgrade pip


In [12]:
import numpy as np
test = np.array([15, 20, 25, 30])
type(test)

numpy.ndarray

In [19]:
print(test)
test +5  #np.array에서 가능해진다. universial function 하나하나 들어가서 계산해준다
print(test/ 2)
#universial function을 위해서는 안에는 모두 같은 자료형이여야한다.


[15 20 25 30]
[ 7.5 10.  12.5 15. ]


In [25]:
#test2 = np.array(['15', 20, '25', True, [1,2,34]])
test2 = np.array(['15', 20, '25', True])
print(test2)
test2
print(test2 +2) #이거 오류난다.
# 넘파이의 배열에는 모두 같은자료형인 원소를 넣습니다. 그렇지 않으면 자신이 모두 포함할수 있는 같은 자료혈으로 변경


['15' '20' '25' 'True']


UFuncTypeError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('int32')) -> None

In [29]:
np.array(list(range(0,10,2)))
#파이썬의 기본 range는 기본 정수배열만 만드는데
#numpy는 아니다

array([0, 2, 4, 6, 8])

In [26]:
test1 = np.arange(15,31,5) # 시작점, 끝+1, 스텝, r이 1개!! #range랑 비슷
test1+1

array([16, 21, 26, 31])

In [32]:
test1 = np.arange(0,1,0.1)
test1 #기존 파이썬 처럼 정수배열이 아니라 소수점도 가능해진다.

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [33]:
dir(test1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_namespace__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__buffer__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',


In [ ]:
#많이 사용하는 함수들 위주로 ㄱ

In [44]:
ndarray = np.array([1,'가',True,{'가':'가위'}]) #r가능은 하지만 이러면 numpy를 쓰지 말아야한다.
ndarray[0]
 #방번호로 호출한다


1

In [47]:
for i in range(len(ndarray)):
    print(type(ndarray[i]))

<class 'int'>
<class 'str'>
<class 'bool'>
<class 'dict'>


In [96]:
ndarray2 = np.array([[1,2,3,4],[5,6,7,8]], dtype ='int8')
ndarray2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]], dtype=int8)

In [97]:
ndarray3 = np.array([1,2,3,256],dtype = 'int8') #데이터타입 정해주기
ndarray3 #int8이라하면 2의 8승 -127 ~ 127까지만 사용가능해진다.


OverflowError: Python integer 256 out of bounds for int8

In [98]:
ndarray2.itemsize #요소1개 즉 방하나의 크기
ndarray2.ndim #몆차원 인지 말해준다 요건 1차월 배열
ndarray2.shape #구조에 대해서 말해준다. 요소4개가 한줄로 있다
ndarray2.size #요소의 개수
ndarray2.strides  #strides = 보폭이라는 뜻 각 요소를 건너뛰기 위해서 몆바이트를 뛰어야하는가


(4, 1)

In [72]:
ndarray2

array([[1., 2., 3., 4.],
       [5., 6., 7., 8.]])

In [74]:
ndarray2.itemsize 

8

In [76]:
ndarray2.ndim

2

In [78]:
ndarray2.shape #2차원이고 4개의 요소를 각각 갖는다

(2, 4)

In [80]:
ndarray2.size #총 8개 요소 들어있음

8

In [82]:
ndarray2.strides 

(32, 8)

In [86]:
np.append(ndarray2,9) # 데이터관련 패키지, 무엇보다 원본을 보존하는게 우선이기 떄문에 일반 파이썬과 달리 값을 추가하는
#append라는 함수가 원본을 파괴하지 않고 결과를 리턴하도록 구현되어 있다.
#원본을 바꿀라면
ndarray2 = np.append(ndarray2,9)
ndarray2  #구조가 1차월 배열로 돌아간다.

array([1., 2., 3., 4., 5., 6., 7., 8., 9., 9.])

In [90]:
ndarray2.T #행렬 열과 행을 변경

array([[1., 5.],
       [2., 6.],
       [3., 7.],
       [4., 8.]])

In [92]:
ndarray2 + 5

array([[ 6.,  7.,  8.,  9.],
       [10., 11., 12., 13.]])

In [101]:
ndarray2 = np.array([[1,2,3,4],[5,6,7,8]], dtype ='int8')
ndarray2
np.append(ndarray2,[9,10,11,12])
ndarray2 = np.append(ndarray2,[9,10,11,12])
ndarray2

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [103]:
ndarray2 = np.array([[1,2,3,4],[5,6,7,8]], dtype ='int8')
ndarray2= np.append(ndarray2.T,[9,10,11,12])
ndarray2

array([ 1,  5,  2,  6,  3,  7,  4,  8,  9, 10, 11, 12])

In [105]:
ndarray2 = np.array([[1,2,3,4],[5,6,7,8]], dtype ='int8')

In [112]:
ndarray2 = np.array([[1,2,3,4],[5,6,7,8]], dtype ='int8')
ndarray2= np.append(ndarray2,[[9,10,11,12]],axis = 0) #axis=0 가로축 axis =1은 세로축

In [113]:
ndarray2 = np.array([[1,2,3,4],[5,6,7,8]], dtype ='int8')
ndarray2= np.append(ndarray2,[[9,10,11,12]],axis = 1) #axis=0 가로축 axis =1은 세로축

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [115]:
ndarray2 = np.array([[1,2,3,4],[5,6,7,8]], dtype ='int8')
ndarray2= np.append(ndarray2,[[9],[10]],axis = 1) #axis=0 가로축 axis =1은 세로축

In [116]:
ndarray2

array([[ 1,  2,  3,  4,  9],
       [ 5,  6,  7,  8, 10]])

In [127]:
test
ndarray = np.arange(15,26,5)
ndarray = np.array([15,20,25])
ndarray

array([15, 20, 25])

In [137]:
print(np.sum(ndarray)) #sum은 ndarray와 호환이 됨
print(np.sum(ndarray) / np.size(ndarray))
print(np.sum(ndarray) / len(ndarray)) #len은 ndarray와 호환이 됨



60
20.0
20.0


In [142]:
np.mean(ndarray)  #평균주는 mean도 호환이 된다.

np.float64(20.0)

In [149]:
ndarray2

array([[ 1,  2,  3,  4,  9],
       [ 5,  6,  7,  8, 10]])

In [145]:
#파이썬의 기본 내장함수 sum은 열기준으로 함해준다.
sum(ndarray2)

array([ 6,  8, 10, 12, 19])

In [147]:
np.sum(ndarray2,axis=0) #행기준으로 더해준다

array([ 6,  8, 10, 12, 19])

In [150]:
np.sum(ndarray2,axis=1) #별도의 행과 열로 합해주기 위한 함수를 따로 쓴다

array([19, 36])

In [155]:
test = test+5
np.mean(test)
test.mean()

np.float64(47.5)

In [159]:
np.sum(test)
test.sum()

np.int64(190)

In [162]:
np.append(test,40)
test

array([40, 45, 50, 55])

In [161]:
test.sum()

np.int64(190)

In [167]:
ndarray2

array([[ 1,  2,  3,  4,  9],
       [ 5,  6,  7,  8, 10]])

In [165]:
ndarray2.cumsum() #누적합 함수

array([ 1,  3,  6, 10, 19, 24, 30, 37, 45, 55])

In [166]:
ndarray3.cumsum()

array([ 1,  3,  6, 10])

In [169]:
ndarray2.var() #분산

np.float64(8.25)

In [171]:
ndarray2.std() #표준편자

np.float64(2.8722813232690143)

In [177]:
ndarray2.argmax(axis = 0) #가장 큰 값이 들어있는 방번호

array([1, 1, 1, 1, 1])

In [175]:
ndarray2.argmin()

np.int64(0)

In [178]:
ndarray2.max()

np.int64(10)

In [180]:
ndarray2

array([[ 1,  2,  3,  4,  9],
       [ 5,  6,  7,  8, 10]])

In [184]:
wrong_example=np.array([[ 1,  2,  3,  4],[ 5,  6,  7,None]])
#None이 없을떄 inhomogeneous 동질하지 않은 모양을 가지고 있어서 만들어지지 않는다. 따라서 이럴떄는 None으로 채워넣는다

In [188]:
wrong_example[1][3]
#wrong_example +5 #None에는 값을 더하거나 뺼수없다

TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

In [190]:
good_example=np.array([[ 1,  2,  3,  4],[ 5,  6,  7,np.nan]])

In [192]:
good_example +5 #값이 없는 구간을 뺴고 더해준다. np.nan은 파이썬의 None과 같은 역활
#자료형이 다를떄 연산이 일괄적으로 가능한데 np.none은 float으로 되어있어서 가능해진다.

array([[ 6.,  7.,  8.,  9.],
       [10., 11., 12., nan]])

In [193]:
type(good_example[1][3])

numpy.float64

In [196]:
#np.inf는 무한대 infinite를 의미한다
wrong_example2 = good_example / 0

C:\Users\PARK\AppData\Local\Temp\ipykernel_15976\3908764638.py:2: RuntimeWarning: divide by zero encountered in divide
  wrong_example2 = good_example / 0


In [197]:
wrong_example2[1][1] #float으로 되어있는 이유는 broadcast를 해야하니깐

np.float64(inf)

In [200]:
np.nan_to_num(good_example) #nan을 0으로 채워준다

array([[1., 2., 3., 4.],
       [5., 6., 7., 0.]])

In [201]:
np.nan_to_num(good_example, nan =1) #특정 수로 채워넣을수도 있다.

array([[1., 2., 3., 4.],
       [5., 6., 7., 1.]])

In [204]:
a = np.arange(0,10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [207]:
b= [0.3,1.3,4.5,2]
b

[0.3, 1.3, 4.5, 2]

In [208]:
np.array(b,dtype='int') #정수 ndarray로 형변환 걍 지수부를 다 버린다.

array([0, 1, 4, 2])

In [211]:
c= [0.3,'1.3',4.5,2]
np.array(c) #str으로 된 자료가 섞여있으면 나머지도 str로 변환

array(['0.3', '1.3', '4.5', '2'], dtype='<U32')

In [213]:
np.array(c,dtype='float')

array([0.3, 1.3, 4.5, 2. ])

In [219]:
b = np.arange(0,9.01,0.1)
np.array(b,dtype='float')

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. , 1.1, 1.2,
       1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2, 2.3, 2.4, 2.5,
       2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5, 3.6, 3.7, 3.8,
       3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8, 4.9, 5. , 5.1,
       5.2, 5.3, 5.4, 5.5, 5.6, 5.7, 5.8, 5.9, 6. , 6.1, 6.2, 6.3, 6.4,
       6.5, 6.6, 6.7, 6.8, 6.9, 7. , 7.1, 7.2, 7.3, 7.4, 7.5, 7.6, 7.7,
       7.8, 7.9, 8. , 8.1, 8.2, 8.3, 8.4, 8.5, 8.6, 8.7, 8.8, 8.9, 9. ])

In [220]:
np.array(b,dtype='int')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 4, 4, 4, 4,
       4, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5, 5, 5, 5, 5, 5, 6, 6, 6, 6, 6, 6,
       6, 6, 6, 6, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 8, 8, 8, 8, 8, 8, 8, 8,
       8, 8, 9])

In [221]:
boolarray=np.array([True,False,True,True,False])
type(boolarray[0])

numpy.bool

In [222]:
boolarray + 1

array([2, 1, 2, 2, 1])

In [224]:
c = np.array([[1,2],[3,4]],'uint')  #uint는 양수만 받는 정수형이다.
c

array([[1, 2],
       [3, 4]], dtype=uint64)

In [225]:
c-3 #양의 정수를 넘어서는 범위에서 이상한 값이 출력된다.

array([[18446744073709551614, 18446744073709551615],
       [                   0,                    1]], dtype=uint64)

# 자료의 형태
- Scalar: 점, 수 하나. 방향이 없고 양만 있는 것
          
        파이썬 - 변하지 않는 숫자 (상수) 정도로 이해

- Vector: 선, 한 열이나 행으로 이뤄진 수 조합
        양과 방향성을 가지고 있는 형태
        파이썬 - 행이 n개이고 열이 1인 형태의 배열

- Matrix : 면,
        여러개의 벡터가 모여서 이룬 하나의 행렬을 의미합니다.


In [229]:
#np.array([0,0,0,0])
np.zeros((1,4)) #한줄짜리 4개

array([[0., 0., 0., 0.]])

In [232]:
np.ones((4,1),dtype='int')  #1만 들어있는거 만들기

array([[1],
       [1],
       [1],
       [1]])

In [240]:
c= np.ones((3,2))
b= np.zeros((3,2),bool)

In [241]:
print(c)
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[False False]
 [False False]
 [False False]]


In [242]:
dir(np.random) # 모듈에 dir함수를 실행하면 모듈안에 작성된 함수/변수명 확인 가능합니다.

['BitGenerator',
 'Generator',
 'MT19937',
 'PCG64',
 'PCG64DXSM',
 'Philox',
 'RandomState',
 'SFC64',
 'SeedSequence',
 '__RandomState_ctor',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_bounded_integers',
 '_common',
 '_generator',
 '_mt19937',
 '_pcg64',
 '_philox',
 '_pickle',
 '_sfc64',
 'beta',
 'binomial',
 'bit_generator',
 'bytes',
 'chisquare',
 'choice',
 'default_rng',
 'dirichlet',
 'exponential',
 'f',
 'gamma',
 'geometric',
 'get_bit_generator',
 'get_state',
 'gumbel',
 'hypergeometric',
 'laplace',
 'logistic',
 'lognormal',
 'logseries',
 'mtrand',
 'multinomial',
 'multivariate_normal',
 'negative_binomial',
 'noncentral_chisquare',
 'noncentral_f',
 'normal',
 'pareto',
 'permutation',
 'poisson',
 'power',
 'rand',
 'randint',
 'randn',
 'random',
 'random_integers',
 'random_sample',
 'ranf',
 'rayleigh',
 'sample',
 'seed',
 'set_bit_generator',
 'set_state',
 'shuf

In [268]:
a = [1,2,3,4,5]
np.random.choice(a,4) #무작위로 선택, 중복도 가능
#복원추출방식이다.

array([3, 4, 1, 4])

In [296]:
np.random.choice(a,4, replace=False) #중복 없앰즉 비복원

#seed로 가장 최초값을 지정가능
# 초기값을 동일하게 지정해서 난수를 생성해서 난수의 결과가 같이 작업하는 사람


array([2, 1, 4, 5])

In [300]:
np.random.seed(42)  #이것으로 인해 출력값이 같아진다.같은코드 셀내에서만 seed를 삼는다.
np.random.choice(a,4, replace=False)

array([2, 5, 3, 1])

In [301]:
np.random.choice(21,4, replace=False) #0에서 20사이에서 4개를 뽑고 비복원으로 해줘


array([ 8, 16,  0, 19], dtype=int32)

In [302]:
np.random.choice(21,(3,7), replace=False) #3행 7열로 뽑아줘

array([[17,  1,  5,  0, 10,  7,  4],
       [12,  8,  3,  6, 19,  2, 18],
       [13, 14, 15,  9, 16, 20, 11]], dtype=int32)

In [305]:
np.random.rand(3,7) #3행 7열로 균등분포의 확률로 0~1사이에서 뽑는다

array([[0.59789998, 0.92187424, 0.0884925 , 0.19598286, 0.04522729,
        0.32533033, 0.38867729],
       [0.27134903, 0.82873751, 0.35675333, 0.28093451, 0.54269608,
        0.14092422, 0.80219698],
       [0.07455064, 0.98688694, 0.77224477, 0.19871568, 0.00552212,
        0.81546143, 0.70685734]])

In [308]:
np.random.randn(1,2) #0에서 1사이 정규분포의 확률로 값을 뽑아낸다.

array([[-0.62347739, -1.50815329]])

In [311]:
np.random.randint(10,20,3) #10에서 20사이에서 3개를 뽑아줘

np.random.randint(10,20,(3,9))  #10에서 20사이에서 3행 9열로 뽑는다.

array([[12, 10, 12, 14, 12, 10, 14, 19, 16],
       [16, 18, 19, 19, 12, 16, 10, 13, 13],
       [14, 16, 16, 13, 16, 12, 15, 11, 19]], dtype=int32)

## 넘파이가 제공하는 통계연산 메소드

In [314]:
a = np.array(a)

In [315]:
a.mean()

np.float64(3.0)

In [319]:
np.average(a,weights=[2,1,1,0,0])   #가중평균도 가능해진다
#a에 0번방에 2를 곱하고 1번방에 1을 곱하고 이런식으로 간다음에 다 더해서 총 가중치 2+1+1+0+0 을 해서 4로 나눈다.


np.float64(1.75)

In [321]:
np.median(a)   #중앙값

np.float64(3.0)

In [325]:
#np.mode(a)  #넘파이에는 최빈값을 구하는 함수는 없다

import statistics as st
st.mode(a)  #statistics에서는 가능
#최빈값의 개수가 동일한 경우 1개만 출력하기에 유의해서 사용해야한다.

np.int64(1)

In [341]:
a= np.random.randint(0,100,20)
np.random.seed(15)
x= np.array(a)
x

array([72, 12,  5,  0, 28, 27, 71, 75, 85, 47, 93, 17, 31, 23, 32, 62, 10,
       15, 68, 39], dtype=int32)

In [342]:
print(x.max(), x.min())

93 0


In [343]:
print(x.argmax(), x.argmin())

10 3


In [345]:
np.mean(x)

np.float64(40.6)

In [349]:
np.sort(x) #원본을 바꿔어버림
x

array([ 0,  5, 10, 12, 15, 17, 23, 27, 28, 31, 32, 39, 47, 62, 68, 71, 72,
       75, 85, 93], dtype=int32)

In [350]:
a= np.random.randint(0,100,20)
np.random.seed(15)
x= np.array(a)
x

array([72, 12,  5,  0, 28, 27, 71, 75, 85, 47, 93, 17, 31, 23, 32, 62, 10,
       15, 68, 39], dtype=int32)

In [351]:
sorted(x)  #원본을 안바꾼다, 파이썬의 sortes함수는 list로 결과가 나온다.

[np.int32(0),
 np.int32(5),
 np.int32(10),
 np.int32(12),
 np.int32(15),
 np.int32(17),
 np.int32(23),
 np.int32(27),
 np.int32(28),
 np.int32(31),
 np.int32(32),
 np.int32(39),
 np.int32(47),
 np.int32(62),
 np.int32(68),
 np.int32(71),
 np.int32(72),
 np.int32(75),
 np.int32(85),
 np.int32(93)]

In [352]:
np.sort(x) #원본을 안바꿈 그냥 x.sort()는 바꿈
x

array([72, 12,  5,  0, 28, 27, 71, 75, 85, 47, 93, 17, 31, 23, 32, 62, 10,
       15, 68, 39], dtype=int32)

In [354]:
x = np.array([100, 3, 20, 50, 80, 4])


In [362]:
np.sort(x)[::-1]

-np.sort(-x)

array([100,  80,  50,  20,   4,   3])

In [366]:
np.array(sorted(x,reverse =True))

array([100,  80,  50,  20,   4,   3])

## 슬라이싱
파이썬 리스트와 유사하게, Numpy 배열도 슬라이싱이 가능합니다.

Numpy 배열은 다차원인 경우가 많기에, 각 차원별로 어떻게 슬라이스할건지 명확히 해야 합니다:

Numpy 배열을 슬라이싱하면, 연속된 값을 가져오기에 결과로 얻어지는 배열은 언제나 원본 배열의 부분 배열입니다.

In [373]:
a = [[ 1 ,2 , 3,  4], [ 5 , 6 , 7 , 8], [ 9 ,10 ,11 ,12]]
a = np.array(a)
a


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [382]:
print(a[0:2, 2:4])
print(a[1:4,1:3])    #당연한것들은 생략가능
print(a[:2,:3])         #행 : 열

[[3 4]
 [7 8]]
[[ 6  7]
 [10 11]]
[[1 2 3]
 [5 6 7]]


다차원배열은 아래와 같은 방법으로 슬라이싱 합니다.
`a[ : , : ]`


`a[행 슬라이싱 시작:행 슬라이싱 끝, 열 슬라이싱 시작:열 슬라이싱 끝]`


**시작값**부터 **끝값** <font color="red">전</font>까지 슬라이싱 됩니다.

## 인덱싱

In [384]:
a[0][3]  #이게 첫번쨰 방법

np.int64(4)

In [390]:
a[[0]]  #0번쨰 행을 가져오기
a[[0,1],]    #0,1번쨰 행 가져오기


array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [397]:
a[[0,2]]
a[::2]

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12]])

In [398]:
a[[0,2,1]]  #순서 바꾸기 슬라이싱으로는 불가능

array([[ 1,  2,  3,  4],
       [ 9, 10, 11, 12],
       [ 5,  6,  7,  8]])

In [399]:
a>3 # bool타입으로 판단 booling indexing

array([[False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [401]:
a[a>3]  #true인것만 나오는데 구조가 무너진다

array([ 4,  5,  6,  7,  8,  9, 10, 11, 12])

In [406]:
b = np.array([True,False,True,False]) #mask

In [409]:
a.T[b]   #마스킹 가능

array([[ 1,  5,  9],
       [ 3,  7, 11]])

In [410]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [414]:
np.where(a>3,3,0)

array([[0, 0, 0, 3],
       [3, 3, 3, 3],
       [3, 3, 3, 3]])

In [415]:
np.where(a>3,a,0)

array([[ 0,  0,  0,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [419]:
#특정조건을 ndarray안의 모든 원소가 만족하면 True,False
np.all(a>0)

np.True_

In [421]:
x2 = [[ np.inf ,2 , 3,  4], [ 5 , 6 , np.nan , 8], [ 9 ,10 ,11 ,12]]

In [424]:
np.isnan(x2)

array([[False, False, False, False],
       [False, False,  True, False],
       [False, False, False, False]])

In [426]:
np.isinf(x2)

array([[ True, False, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [428]:
np.isfinite(x2)   #nan inf를 false로 처리

array([[False,  True,  True,  True],
       [ True,  True, False,  True],
       [ True,  True,  True,  True]])

In [440]:
c= a.copy()

In [441]:
a[0:2,0:2]
a1 = a[0:2,0:2]
a1

array([[100,   2],
       [  5,   6]])

In [442]:
a1[0][0] = 100

In [443]:
a  #원본도 바뀜

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [444]:
c

array([[100,   2,   3,   4],
       [  5,   6,   7,   8],
       [  9,  10,  11,  12]])

In [445]:
c[[0,1]]

array([[100,   2,   3,   4],
       [  5,   6,   7,   8]])

In [469]:
a= np.array([[[10, 11, 12],[13, 14, 15],[16,17,18]],[[20, 21, 22],
    [23, 24, 25],[26,27,28]],
   [[30, 31, 32],
    [33, 34, 35],[36,37,38]]])  
a

array([[[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[20, 21, 22],
        [23, 24, 25],
        [26, 27, 28]],

       [[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

In [473]:
print(np.shape(a))
print('차원확인',np.ndim(a),'차원')
print(a.itemsize)
print(a.size)
print(a.strides) #차원별로 넘어가기 위한 크기
print('')

(3, 3, 3)
차원확인 3 차원
8
27
(72, 24, 8)


In [463]:
np.where(a==14,True,0)


array([[[0, 0, 0],
        [0, 1, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]],

       [[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]]])

In [466]:
a[2:3,:3,:3]

array([[[30, 31, 32],
        [33, 34, 35],
        [36, 37, 38]]])

In [474]:
a[:3,(0,1,),:3]

array([[[10, 11, 12],
        [13, 14, 15]],

       [[20, 21, 22],
        [23, 24, 25]],

       [[30, 31, 32],
        [33, 34, 35]]])

In [523]:
k=a[:3,(0,1,),:3].flatten() #구조를 무너뜨려 1차원으로 평탄화
k

array([10, 11, 12, 13, 14, 15, 20, 21, 22, 23, 24, 25, 30, 31, 32, 33, 34,
       35])

In [480]:
b= a[:3,(0,1,),:3] #재구조화 


In [483]:
b.reshape(3,6) #3행 6열로 구조화


array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35]])

In [485]:
b.reshape(3,3,2)

array([[[10, 11],
        [12, 13],
        [14, 15]],

       [[20, 21],
        [22, 23],
        [24, 25]],

       [[30, 31],
        [32, 33],
        [34, 35]]])

In [524]:
k.reshape(2,3,-1)   #-1을 넣는다는 건 배열의 개수를 모를때 나머지 차원을 잘 맞춰달라는 것
#애매한 자리에 채워넣기

array([[[10, 11, 12],
        [13, 14, 15],
        [20, 21, 22]],

       [[23, 24, 25],
        [30, 31, 32],
        [33, 34, 35]]])

In [515]:
a[(a<30) & (a>15)]

array([16, 17, 18, 20, 21, 22, 23, 24, 25, 26, 27, 28])

In [525]:
np.insert(k,10,(1,1,1))

array([10, 11, 12, 13, 14, 15, 20, 21, 22, 23,  1,  1,  1, 24, 25, 30, 31,
       32, 33, 34, 35])

In [530]:
c= np.array([1,2,3,4,5,6])
np.insert(c,2,10)  #insert(배열 이름, 자리, 값)


array([ 1,  2, 10,  3,  4,  5,  6])

In [533]:
np.insert(a,(1,2,3),25) #원본이 달리지는게 아니라 한번 보여주는 것

array([10, 25, 11, 25, 12, 25, 13, 14, 15, 16, 17, 18, 20, 21, 22, 23, 24,
       25, 26, 27, 28, 30, 31, 32, 33, 34, 35, 36, 37, 38])

In [537]:
d=c.reshape(2,3)
d

array([[1, 2, 3],
       [4, 5, 6]])

In [543]:
np.insert(d,np.size(d),[7,8,9])


array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [545]:
np.insert(d,2,[7,8,9],axis=0) #행기준으로 삽입



array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [547]:
np.insert(d,3,[7,8],axis=1)


array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

## 연결 - concatenate


In [ ]:
#수만 맞으면 연결해줌
[16,17,18] , [20,30]

In [548]:
np.concatenate((d,[[16,17,18]]),axis =0)
#concatenate(변수이름, 넣을거, 기준axis =0---> 행기준)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [16, 17, 18]])

In [551]:
np.concatenate((d,[[20],[30]]),axis =1)  #차원이 일치해야한다

array([[ 1,  2,  3, 20],
       [ 4,  5,  6, 30]])

브로트캐스팅은 Numpy에서 shape가 다른 배열 간에도 산술 연산이 가능하게 하는 메커니즘입니다. 종종 작은 배열과 큰 배열이 있을 때, 큰 배열을 대상으로 작은 배열을 여러 번 연산하고자 할 때가 있습니다. 예를 들어, 행렬의 각 행에 상수 벡터를 더하는 걸 생각해보세요. 이는 다음과 같은 방식으로 처리될 수 있습니다:

In [555]:
d+1

array([[2, 3, 4],
       [5, 6, 7]])

In [556]:
d

array([[1, 2, 3],
       [4, 5, 6]])

In [554]:
d+[1,2,3]

array([[2, 4, 6],
       [5, 7, 9]])

In [557]:
#.npy 라는 바이너리 파일로 연산한 데이터를 저장할수 있다.
np.save('a.npy',d)   

In [559]:
y = np.load('a.npy')  #저장된 바이너리 파일 불러오기

In [560]:
y

array([[1, 2, 3],
       [4, 5, 6]])